<div style="text-align: center;">
<span style="font-family:Courier New; font-size:18px;">
Machine learning approach on gross agricultural production dataset<br>
20/05/2026<br>
Petar Tumbas Fanny Hakim <br><br>
</span>
</div>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<span style="font-family:Courier New; font-size:20px;">
<b>Part 1.</b> <br>
<b>What Data and Why this Data</b>
</span>

blablablabla

<span style="font-family:Courier New; font-size:20px;">
<b>Part 2.</b> <br>
<b>Data import and inspection</b>
</span>

In [14]:
data = pd.read_csv("FAO_PIN_Merged.csv")
data.head(10)
# data.tail(10)

,Country or Area,element_code,Element,Year,Unit,Value,category
0,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2021,Int. $,113.74,Food_PIN
1,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2020,Int. $,118.09,Food_PIN
2,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2019,Int. $,112.55,Food_PIN
3,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2018,Int. $,96.07,Food_PIN
4,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2017,Int. $,100.02,Food_PIN
5,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2016,Int. $,102.34,Food_PIN
6,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2015,Int. $,95.99,Food_PIN
7,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2014,Int. $,101.67,Food_PIN
8,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2013,Int. $,94.29,Food_PIN
9,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2012,Int. $,97.21,Food_PIN

In [3]:
print(data.shape) #(rows, columns)
print(data.columns)
print(data.dtypes)

(52652, 7)
Index(['Country or Area', 'element_code', 'Element', 'Year', 'Unit', 'Value',
       'category'],
      dtype='object')
Country or Area     object
element_code         int64
Element             object
Year                 int64
Unit                object
Value              float64
category            object
dtype: object

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52652 entries, 0 to 52651
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country or Area  52652 non-null  object
 1   element_code     52652 non-null  int64
 2   Element          52652 non-null  object
 3   Year             52652 non-null  int64
 4   Unit             52652 non-null  object
 5   Value            52652 non-null  float64
 6   category         52652 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 2.8+ MB

In [5]:
data.count()

Country or Area    52652
element_code       52652
Element            52652
Year               52652
Unit               52652
Value              52652
category           52652
dtype: int64

In [6]:
# pd.set_option('display.max_rows', None)
data['Country or Area']

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
            ...
52647       Zimbabwe
52648       Zimbabwe
52649       Zimbabwe
52650       Zimbabwe
52651       Zimbabwe
Name: Country or Area, Length: 52652, dtype: object

In [7]:
data['Country or Area'].unique() # we need to separate areas and conuntries

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Americas',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Asia',
       'Australia', 'Australia and New Zealand', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Caribbean', 'Central African Republic',
       'Central America', 'Central Asia', 'Chad', 'Chile', 'China',
       'China, Hong Kong SAR', 'China, Macao SAR', 'China, mainland',
       'Other non-specified areas', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba',
       'Cyprus', 'Czechia', "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Eastern Africa', 'Eastern Asia',
       'Eastern Europe', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
       'Europe', 'European Union (27)', 'Faroe Islands', 'Fiji',
       'Finland', 'France', 'French Polynesia', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', 'Land Locked Developing Countries',
       "Lao People's Democratic Republic", 'Latvia',
       'Least Developed Countries', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Lithuania', 'Low Income Food Deficit Countries',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Melanesia', 'Mexico', 'Micronesia',
       'Micronesia (Federated States of)', 'Middle Africa', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Net Food Importing Developing Countries',
       'Netherlands (Kingdom of the)', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North Macedonia',
       'Northern Africa', 'Northern America', 'Northern Europe', 'Norway',
       'Oceania', 'Oman', 'Pakistan', 'Palestine', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Polynesia', 'Portugal', 'Puerto Rico', 'Qatar',
       'Republic of Korea', 'Republic of Moldova', 'Romania',
       'Russian Federation', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Small Island Developing States', 'Solomon Islands', 'Somalia',
       'South Africa', 'South America', 'South Sudan',
       'South-eastern Asia', 'Southern Africa', 'Southern Asia',
       'Southern Europe', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan',
       'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Türkiye', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Western Africa',
       'Western Asia', 'Western Europe', 'World', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [8]:
data.describe()

       element_code          Year         Value
count  52652.000000  52652.000000  52652.000000
mean     293.000000   1992.111905     92.828808
std      141.001339     17.624093     74.124524
min      152.000000   1961.000000      3.080000
25%      152.000000   1977.000000     63.670000
50%      293.000000   1993.000000     89.820000
75%      434.000000   2007.000000    104.200000
max      434.000000   2021.000000   2056.200000

In [15]:
data['category'].unique()

array(['Food_PIN', 'Agri_PIN'], dtype=object)

In [ ]:
Food_data = data[data['category'] == 'Food_PIN']
Agri_data = data[data['category'] == 'Agri_PIN'].reset_index(drop=True)

In [19]:
Food_data.info()
Agri_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26326 entries, 0 to 26325
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country or Area  26326 non-null  object
 1   element_code     26326 non-null  int64
 2   Element          26326 non-null  object
 3   Year             26326 non-null  int64
 4   Unit             26326 non-null  object
 5   Value            26326 non-null  float64
 6   category         26326 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 1.6+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 26326 entries, 26326 to 52651
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country or Area  26326 non-null  object
 1   element_code     26326 non-null  int64
 2   Element          26326 non-null  object
 3   Year             26326 non-null  int64
 4   Unit             26326 non-null  object
 5   Value            26326 non-null  float64
 6   category         26326 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 1.6+ MB

In [23]:
Food_data.tail(10)

,Country or Area,element_code,Element,Year,Unit,Value,category
26316,Zimbabwe,434,Gross per capita Production Index Number (2014...,1970,Int. $,77.50,Food_PIN
26317,Zimbabwe,434,Gross per capita Production Index Number (2014...,1969,Int. $,81.44,Food_PIN
26318,Zimbabwe,434,Gross per capita Production Index Number (2014...,1968,Int. $,69.24,Food_PIN
26319,Zimbabwe,434,Gross per capita Production Index Number (2014...,1967,Int. $,81.53,Food_PIN
26320,Zimbabwe,434,Gross per capita Production Index Number (2014...,1966,Int. $,77.62,Food_PIN
26321,Zimbabwe,434,Gross per capita Production Index Number (2014...,1965,Int. $,69.18,Food_PIN
26322,Zimbabwe,434,Gross per capita Production Index Number (2014...,1964,Int. $,70.25,Food_PIN
26323,Zimbabwe,434,Gross per capita Production Index Number (2014...,1963,Int. $,72.83,Food_PIN
26324,Zimbabwe,434,Gross per capita Production Index Number (2014...,1962,Int. $,78.95,Food_PIN
26325,Zimbabwe,434,Gross per capita Production Index Number (2014...,1961,Int. $,75.07,Food_PIN

In [26]:
Agri_data.head(10)

,Country or Area,element_code,Element,Year,Unit,Value,category
26326,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2021,Int. $,113.91,Agri_PIN
26327,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2020,Int. $,118.23,Agri_PIN
26328,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2019,Int. $,112.99,Agri_PIN
26329,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2018,Int. $,96.41,Agri_PIN
26330,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2017,Int. $,99.92,Agri_PIN
26331,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2016,Int. $,102.40,Agri_PIN
26332,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2015,Int. $,96.07,Agri_PIN
26333,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2014,Int. $,101.53,Agri_PIN
26334,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2013,Int. $,94.31,Agri_PIN
26335,Afghanistan,152,Gross Production Index Number (2014-2016 = 100),2012,Int. $,97.14,Agri_PIN

In [27]:
Food_data = Food_data.drop(columns=['Element','Unit','category'])
Agri_data = Agri_data.drop(columns=['Element','Unit','category'])

In [28]:
# pd.set_option('display.max_rows', None)
# pd.reset_option('display.max_rows')
Food_data #essentially this is the final dataset we will need

      Country or Area  element_code  Year   Value
0         Afghanistan           152  2021  113.74
1         Afghanistan           152  2020  118.09
2         Afghanistan           152  2019  112.55
3         Afghanistan           152  2018   96.07
4         Afghanistan           152  2017  100.02
...               ...           ...   ...     ...
26321        Zimbabwe           434  1965   69.18
26322        Zimbabwe           434  1964   70.25
26323        Zimbabwe           434  1963   72.83
26324        Zimbabwe           434  1962   78.95
26325        Zimbabwe           434  1961   75.07

[26326 rows x 4 columns]

In [12]:
Areas = [
    'Africa'
    'Americas'
    'Asia'
    'Australia and New Zealand'
    'Central America'
    'Central Asia'
    'China, mainland'
    'Other non-specified areas'
    'Eastern Africa'
    'Eastern Asia'
    'Eastern Europe'
    'Europe'
    'European Union (27)'
    'Land Locked Developing Countries'
    'Least Developed Countries'
    'Low Income Food Deficit Countries'
    'Micronesia (Federated States of)'
    'Middle Africa'
    'Net Food Importing Developing Countries'
    'Northern Africa'
    'Northern America'
    'Northern Europe'
    'Oceania'
    'Polynesia'
    'Small Island Developing States'
    'South America'
    'South-eastern Asia'
    'Southern Africa'
    'Southern Asia'
    'Southern Europe'
    'Western Africa'
    'Western Asia'
    'Western Europe'
    'World'
]